### ISSUE TITLE
Then performance of DFM is over qualified

### ISSUE THREAD

**Issue by Snnzhao** [Veason-silverbullet/NNR#2]
I test DFM on MIND-small. Find the performance of DFM outperforms all the baselines except your proposed model.
This is puzzling, since DFM is proposed in 2018 and the framework is naive. 
Do you have similar situation? Could you share your thinking on this?

**Comment by Veason-silverbullet** [comment]
This may be because that I always tried to optimize the baselines. In some cases, the baselines are over-optimized (e.g., NRMS). Especially, I found that some models are fit to small dataset, i.e., MIND-small. For details, you can contact me via my email zmmao@se.cuhk.edu.hk.

**Comment by Snnzhao** [comment]
Thanks
