### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by whonor** [Veason-silverbullet/NNR#3]
When I run this code on the torch-1.10.1, facing the issue as follows: 

> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [400, 1]], which is output 0 of TBackward, is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

This points to the code in trainer.py:
`loss.backward()`
But the code is worked on the torch-1.9.0.

**Comment by Veason-silverbullet** [comment]
Hi, @whonor .

We find the problem stemming from torch-1.10 (and 1.11) inplace operation on computing graph construction. To solve the problem, we change the code of layers.py (in [line 291](https://github.com/Veason-silverbullet/NNR/blob/5dd9f16c8cbe8ecec21ae3d77afde52af440399b/layers.py#L291)). Specifically, we change this code from
`out += feature # inplace operation`
to
`out = out + feature # non-inplace operation`

Please pull and run the latest code. Thanks.

**Comment by Veason-silverbullet** [comment]
Hi, @whonor .

We found the issues you reported also occurred in some baseline models in the context of torch-1.11. We have fixed the issues and recommend you to full the latest code if you are using it. Besides, we shorten the epoch to reduce training time in this version.
