### ISSUE TITLE
Errors in Libfm

### ISSUE THREAD

**Issue by whonor** [Veason-silverbullet/NNR#4]
I try to run libfm in general recommendation methods, but the `os.system` in libfm_main.py doesn't work as I get an error as follows:

> FileNotFoundError: [Errno 2] No such file or directory: './test/res/libfm/1/libfm'

I run this code on Ubunutu 20.4 and windows10 respectively, but the same problem.
How should I do?

**Comment by Veason-silverbullet** [comment]
Hi @whonor ,

The error stems from our old experimental path settings and permission denial of running libfm. We solved this issue in the latest commit, please pull the latest code, delete the cache files and upgrade assess permission of the `libfm` directory:

`git pull && cd general_recommendation_methods`
`rm *.pkl *.libfm *.txt`
`chmod -R 777 libfm`

Many thanks.
