### ISSUE TITLE
Unable to download wiki-data graph

### ISSUE THREAD

**Issue by Ofir408** [Veason-silverbullet/NNR#5]
I saw you have:
"wget -O wikidata-graph.zip https://mind201910.blob.core.windows.net/knowledge-graph/wikidata-graph.zip"
However when I do this I got an error message: 
HTTP request sent, awaiting response... 409 Public access is not permitted on this storage account.

How can I install the wikidata-graph you used to run your code?

**Comment by Veason-silverbullet** [comment]
This issue was answered by the email for the same question. Here, I paste the email reply for future reference.

> Dear Ofir,
> 
> The knowledge-graph weights were from the Microsoft Recommender repo (see https://github.com/recommenders-team/recommenders/issues/1246). As discussed in the link, the official developer has updated the KG weights, you may refer to https://github.com/recommenders-team/recommenders/blob/main/examples/01_prepare_data/wikidata_knowledge_graph.ipynb for getting the latest KG weights. Thanks for your question.
> 
> Regards,
> 
> MAO, Zhiming
